version: '3'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: 'lend_nws'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pass --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: 
      context: .
      target: app
    container_name: app
    depends_on:
      - db
    # environment:
    #   DB_HOST: mysql://db:3306
    ports:
      - 3000:3000
  api:
    build:
      context: .
      target: api
    container_name: api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
volumes:
  db-data: