on: [push]

name: Build image & Test

jobs:
  test:
    name: Testing my api
    runs-on: ubuntu-latest

    # Testing my nodejs api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test test/test.js
      - name: Build image
        run: docker build -t my-api .
      - name: Run image
        run: docker run -d -p 3001:3001 my-api
      - name: Test image
        run: curl http://localhost:3000

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   - name: Run docker-compose
    #     run: docker-compose up -d
    #   - name: Test
    #     run: |
    #       docker-compose exec mat-api npm run test test/test.js
    #   - name: Stop docker-compose
    #     run: docker-compose down



  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fabienlpt/api:latest
          target: api

      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fabienlpt/app:latest
          target: app

