on: [push]

name: Build image & Test

jobs:
  test:
    name: Testing my api with docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Test
        run: |
          docker-compose exec mat-api npm run test/test.js
      - name: Stop docker-compose
        run: docker-compose down

      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Setup Docker compose
      #   uses: docker-practice/actions-setup-docker-compose@master
      # - name: Build image
      #   run: docker-compose up -d
      # - name: Test my api
      #   run: |
      #     docker-compose exec mat-api
      #     npm test test/test.js

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fabienlpt/api:latest
          target: api

      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fabienlpt/app:latest
          target: app

